name: Azure Terraform CI

on:
  pull_request:
    paths:
      - "project-01/azure/week-04/**"

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
  env:
      TF_VAR_resource_group_name: "cloudclimb-project01-dev-rg"
      TF_VAR_location: "eastus"

      TF_VAR_vnet_name: "cloudclimb-project01-vnet"
      TF_VAR_vnet_address_space: '["10.10.0.0/16"]'

      TF_VAR_app_subnet_name: "cloudclimb-project01-app-subnet"
      TF_VAR_app_subnet_prefix: "10.10.1.0/24"

      TF_VAR_data_subnet_name: "cloudclimb-project01-data-subnet"
      TF_VAR_data_subnet_prefix: "10.10.2.0/24"

      TF_VAR_management_subnet_name: "cloudclimb-project01-management-subnet"
      TF_VAR_management_subnet_prefix: "10.10.3.0/24"

      TF_VAR_ssh_source_ip: "203.0.113.10/32"
      TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}

      TF_VAR_postgres_admin_username: "pgadminuser"
      TF_VAR_postgres_admin_password: ${{ secrets.TF_VAR_POSTGRES_ADMIN_PASSWORD }}

      TF_VAR_tags: '{"Environment":"Development","ManagedBy":"Terraform","Owner":"CloudClimb","Project":"CloudClimb-Project01","Purpose":"CloudClimb-Lab"}'

    defaults:
      run:
        working-directory: project-01/azure/week-04/reference-solution

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Plan
        run: terraform plan -input=false
